backend:
  name: git-gateway
  branch: jekyll
media_folder: 'assets/uploads'
collections: 
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Home Page"
        name: "home"
        file: "index.md"
        fields:
          - {lable: Title, name: title, widget: hidden, default: home}
          - {lable: Layout, name: layout, widget: hidden, default: page}
          - {label: Body, name: body, widget: markdown}
  - label: "Prices"
    name: "prices"
    folder: "_data/prices"
    create: true
    identifier_field: start
    fields: 
      - {label: "Start", name: "start", widget: "date", format: "DD MMMM YYYY", date_format: "DD MMMM YYYY"}
      - {label: "End", name: "end", widget: "date", format: "DD MMMM YYYY", date_format: "DD MMMM YYYY"}
      - {label: "Price", name: "price", widget: "number", value_type: "int", step: 1, min: 0}