backend:
  name: git-gateway
media_folder: 'assets/uploads'
collections: 
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.md"
        fields:
          - {label: Text, name: text, widget: markdown}